version: 2.1
jobs:
  build:
    docker:
      - image: 'cimg/node:16.14'
    steps:
      - 'checkout'
      - restore_cache:
          key: 'yarn-packages-{{ checksum "yarn.lock" }}'
      - run: 'yarn install --frozen-lockfile'
      - save_cache:
          key: 'yarn-packages-{{ checksum "yarn.lock" }}'
          paths:
            - '~/.cache/yarn'
      - run: 'yarn ci'
