'use strict'

const R = require('ramda')

const decodeIgnoreSyncFile = require('./decodeIgnoreSyncFile')
const github = require('./utils/github')
const highlightComments = require('./utils/highlightComments')
const readFileFromProjectRoot = require('./readFileFromProjectRoot')
const {dynamicComposeP, promiseMap} = require('./utils/ramdaHelper')

const isGithubSource = R.test(/^(\w+\/\w+)$/i)
const joinLinesWithEOF = R.compose(R.concat(R.__, '\n'), R.trim, R.join('\n'))
const prependAlert = R.concat([
  highlightComments(
    R.join('\n', [
      'GENERATED BY IGNORE-SYNC, DO NOT EDIT!!!',
      'https://github.com/foray1010/ignore-sync'
    ])
  ),
  ''
])
const sourceIs = (...args) => R.compose(...args, R.prop('source'))

const inlineSourceFetcher = R.compose(joinLinesWithEOF, R.prop('data'))
const githubSourceFetcher = async (block) => {
  const [owner, repo] = block.source.split('/')
  const files = await promiseMap(
    (relativePath) => github.getContentFile(owner, repo, relativePath),
    block.data
  )
  return joinLinesWithEOF(files)
}
const localSourceFetcher = async (block, projectRoot) => {
  const files = await promiseMap(readFileFromProjectRoot(projectRoot), block.data)
  return joinLinesWithEOF(files)
}

module.exports = (ignoreSyncFile, projectRoot) => {
  const fetchIgnorePatternsBySource = promiseMap(
    R.cond([
      [sourceIs(R.equals('inline')), inlineSourceFetcher],
      [sourceIs(R.equals('local')), (block) => localSourceFetcher(block, projectRoot)],
      [sourceIs(isGithubSource), githubSourceFetcher],
      [
        R.T,
        (block) => {
          throw new Error(`unknown source: ${block.source}`)
        }
      ]
    ])
  )

  return dynamicComposeP(
    joinLinesWithEOF,
    prependAlert,
    fetchIgnorePatternsBySource,
    decodeIgnoreSyncFile
  )(ignoreSyncFile)
}
